export const BURGER_INGREDIENTS_REQUEST: 'BURGER_INGREDIENTS_REQUEST' = 'BURGER_INGREDIENTS_REQUEST';
export const BURGER_INGREDIENTS_SUCCESS: 'BURGER_INGREDIENTS_SUCCESS' = 'BURGER_INGREDIENTS_SUCCESS';
export const BURGER_INGREDIENTS_FAILED: 'BURGER_INGREDIENTS_FAILED' = 'BURGER_INGREDIENTS_FAILED';